### PR TITLE
Fixed readBool reader producing a RangeError exception

### PR DESCRIPTION
**Pull request by Citizen01**
**readInt8** method is expecting an **offset (uint)** as 1st argument instead of the **buffer**.
Method was failing at **checkOffset** by throwing an **'offset is not uint'** range error.

### CODE REVIEW

**Comment by Citizen01** [comment]
Any idea as of why my PR doesn't pass the tests on your Jenkins ?
Works on my side:

```
C:\workspace\sigfox-parser [patch-1 =]> npm run test:ci

> @waylay/sigfox-parser@1.1.0 test:ci C:\workspace\sigfox-parser
> npm run lint && tap test/*.test.js --coverage --coverage-report=lcov

> @waylay/sigfox-parser@1.1.0 lint C:\workspace\sigfox-parser
> standard .

test/parser.test.js ................................. 10/10
total ............................................... 10/10

  10 passing (1s)
  ok
```

**Comment by gillesdemey** [comment]
@Citizen01 I've just enabled Travis for this repository, I'll restart the build and it should show green :)

**Comment by francisdb** [comment]
Jenkins was failing because of this:

```
Auto-merging readers/readBool.js
CONFLICT (content): Merge conflict in readers/readBool.js
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by gillesdemey** [comment]
Merged, thanks! 🎉

**Pull request merged**
